### ISSUE TITLE
Message handling

### ISSUE THREAD

**Issue by kissmyjazz** [nwilming/pyedfread#2]
Hi Niklas,
After I first contacted it seemed that messages issue was resolved. But now I looked more closely and I have trouble again. I changed my messages sent to the Eyetracker into the following format `('evt' <number>  <some optional parameters>)`.
So sometimes I have  just evt + number, as ASC file shows it 
`MSG	2942669 evt 02`

and sometime message is appended with the information about the stimulus being shown
`MSG	2945657 evt 06 0, 16, 141408946567 ` 

So I try to read that file into Pandas data frame from ipython, below is my code:
```
import sys
import numpy as np
import pandas
sys.path.append('/usr/local/lib/python2.7/site-packages/pyedfread')
import edf
events, messages = edf.pread('/Users/lizard/Downloads/01141401.edf', ignore_samples=False, filter=['evt'])
```
I also tried `filter = ['all']`

Result is the same messages data frame is empy and no 'evt' column is added to the events data frame

`print messages`

```
Empty DataFrame
Columns: []
Index: []
```

In an unrelated note, I am also missing the pupil area information in the main data frame which I am quite sure the eye-tracker is saving. Eye-tracker is Eyelink 1000 Plus if that matters. I have attached the edf and acs files
[EyelinkRecordingDenis.zip](https://github.com/nwilming/pyedfread/files/112029/EyelinkRecordingDenis.zip)

**Comment by nwilming** [comment]
Hi,

RE point No. 1: 

I can't reproduce what you are seeing with the data files that you sent me. If I run:

```
import edf
e,m = edf.pread('01141401.edf',  
                filter='all',
                properties_filter=['pa'])
print m.evt
print m.evt_time 
```
I get the following output:
```
0    [1.0, 2.0, [04, 0,, 16,, 141405961363\n], [06,...
Name: evt, dtype: object
0    [2941181, 2942669, 2942672, 2945657, 2945659, ...
Name: evt_time, dtype: object
```
Could you try to grab the latest pyedfread version and run the code above on your machine?

RE point No. 2: You have to tell pyedfread that you want the pupil area from the edf. You do this by adding 'pa' to the properties_filter (e.g.` properties_filter=['pa', 'type', 'time', 'sttime', 'entime', 'gx', 'gy', 'gstx', 'gsty', 'genx', 'geny', 'gxvel', 'gyvel', 'start', 'end', 'gavx',  'gavy']`). I should really include it in the default list.

HTH

**Comment by kissmyjazz** [comment]
Thank you so much, I do not know where the problem was, maybe I did not reload my Ipython notebook properly, but now it looks like the code works the same way as on your computer. Sorry for the stupid question, but how can I unpack the messages data frame. Now it looks not very useful: `[1.0, 2.0, [04, 0,, 16,, 141405961363\n], ...`
In ASC file it looks more readable evt 04 0, 16, 141405961363. So should I omit any commas and new line characters when sending messages or there is a way to format the third message part that will make parsing it easy?

**Comment by nwilming** [comment]
The problem with this message formats is that pyedfread does not know a priori how to unpack it. That's why you have to do it yourself. 

The 'standard' way to format your messages would be:

- Chunk your data stream into trials. Each trial will be put into a different row of the resulting data frames. To start a trial send a 'TRIALID' message. 
-  Put optional values into separate messages. If you give these messages meaningful names, and make sure that each message type occurs only once per trial, you'll get a data frame where rows encode trials and columns your messages. If you don't send a message within a trial it's value defaults to nan (I think).

In your case you have to do a bit of data wrangling yourself. If you look at the evt field, you'll see that it contains one entry which is a list with all your messages. So if you do:
```
>>> e,m = edf.pread('/Users/nwilming/Downloads/EyelinkRecordingDenis/01141401.edf', filter='all', >>> properties_filter=['pa', 'start'])
>>> [float(x.replace(',','')) for x in m.evt[0][3]]
[6.0, 0.0, 16.0, 141408946567.0]
```
You get message values of the third message formatted as a list of numbers.

PS: When you recompile cython code it is not straightforward to reload the module. You either have to use jupyters cython magic (which I have never used) or some pyximport magic. But I don't remember the details at the moment.
